spring:
  application:
    name: rabbitmq
  profiles:
    active: 'default'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
server:
  port: 9000
app:
  id: demoApollo
# set apollo meta server address, adjust to actual address if necessary
apollo:
  meta: http://127.0.0.1:8080
rabbitmqdemo: