spring:
  application:
    name: rabbitmq
  profiles:
    active: 'default'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: mike
    password: mike
server:
  port: 8080
rabbitmqdemo: