spring:
  profiles:
    active: 'default'
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      username: root
      password: root
      database: gis
swagger:
  basePackage: com.hongghe.mongodb.controller
  title: 用户服务
  description: 用户基本增删改查
  version: V1.0
